CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(100) NOT NULL,
  password VARCHAR(100) NOT NULL
);

CREATE TABLE keys (
  id INT AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(100) NOT NULL,
  used_by VARCHAR(100)
);

INSERT INTO keys (code) VALUES
('EXTAZYYDLC-1234-7'),
('EXTAZYYDLC-4321-14'),
('EXTAZYYDLC-TEST-30');
